AWSTemplateFormatVersion: "2010-09-09"

Description: EC2 Instance Template.


Parameters:

  PublicSubnet1:
    Description: Public Subnet ID 1 in this VPC.
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet2:
    Description: Public Subnet ID 2 in this VPC.
    Type: AWS::EC2::Subnet::Id

  PublicSubnet3:
    Description: Public Subnet ID 3 in this VPC.
    Type: AWS::EC2::Subnet::Id
  
  DatabaseIP:
    Description: Private IP of the Database Server.
    Type: String

  WebSG:
    Description: Web Secuirty Group in this VPC.
    Type: AWS::EC2::SecurityGroup::Id

  TargetGroup:
    Description: Target Group of ALB.
    Type: String

  Environment:
    Type: String
    Description: Select the appropriate environment
    AllowedValues:
      - dev
      - test
      - prod



Resources:
  JehangirCFWordpressLT:
      Type: AWS::EC2::LaunchTemplate
#      DependsOn: !GetAtt DBStack.Outputs.JehangirCFDBServer
      Properties: 
        LaunchTemplateName: JehangirCFWordpressLT
        LaunchTemplateData:
          ImageId: ami-00399ec92321828f5
          InstanceType: t2.micro
          KeyName: JehangirKP
          SecurityGroupIds: 
            - !Ref WebSG
          UserData:
            Fn::Base64:
              Fn::Sub:
                - |
                  #!/bin/bash
                  set -x
                  apt update -y
                  apt upgrade -y
                  apt install apache2 -y
                  apt install php -y
                  apt install php-mysql -y
                  cd /var/www/html
                  wget https://wordpress.org/latest.zip
                  apt install unzip
                  unzip latest.zip
                  chown -R $USER:$USER /var/www
                  rm index.html
                  cp -r wordpress/* /var/www/html/
                  rm -rf wordpress
                  rm latest.zip
                  service apache2 restart
                  cp /var/www/html/wp-config-sample.php  /var/www/html/wp-config.php
                  sed -i -e 's/database_name_here/mydatabase/g' /var/www/html/wp-config.php
                  sed -i -e 's/username_here/admin/g' /var/www/html/wp-config.php
                  sed -i -e 's/password_here/wordpress/g' /var/www/html/wp-config.php
                  sed -i -e "s/localhost/${DBIP}/g" /var/www/html/wp-config.php
                  service apache2 restart
                - DBIP: !Ref DatabaseIP
  


  JehangirCFASG:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AutoScalingGroupName: JehangirCFASG
        MinSize: "2"
        MaxSize: "3"
        DesiredCapacity: "2"
        HealthCheckGracePeriod: 200
        LaunchTemplate:
          LaunchTemplateId: !Ref JehangirCFWordpressLT
          Version: !GetAtt JehangirCFWordpressLT.LatestVersionNumber
        VPCZoneIdentifier:
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2
          - !Ref PublicSubnet3
        TargetGroupARNs:
          - !Ref TargetGroup
        Tags:
          - Key: Name
            Value: 
              Fn::Sub: JehangirCFASG-${Environment}
            PropagateAtLaunch: true